language: php
php:
  - 7.2
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.testing .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
    - develop
